name: (K8s-db-collector) repo
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update repo trivy-db-update
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Setup github user email and name
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Compile K8s-db-collector
        run: go build -o K8s-db-collector .

      - if: always()
        name: k8s-api
        run: ./K8s-db-collector -target k8s-api
